spring:
  profiles:
    active: DEV
  application:
    name: HelloWorldMS_${spring.profiles.active}
server:
  port: 8762

eureka: 
  instance: 
    status-page-url: http://192.168.52.196:8762/info
    health-check-url: http://192.168.52.196:8762/health
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://192.168.52.196:8761/eureka
      healthcheck: 
        enabled: true      